// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itiwjplrqofpkquahhyk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0aXdqcGxycW9mcGtxdWFoaHlrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU2MDI1NjQsImV4cCI6MjA3MTE3ODU2NH0.IF15GGujyYM4Xp_-8AZDW2edcVIZQD1wsrJU2Tns3SQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});